// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ktiybnnrketqovmlizqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0aXlibm5ya2V0cW92bWxpenFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODE5MjUsImV4cCI6MjA2NDA1NzkyNX0.toBoeiUIl7Ok5NsoUcNKnr9Z58L4AV5tbfdYQOYIQu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);